フェードイン、フェードアウト、カラーフェイド
human-osaka-game-2020/ActionGame_ono pull request #3
Opened 2020-10-14 03:55 UTC by ono-hikaru81

2020-10-14 03:58 UTC, taishi-matsumura commented
@ono-hikaru81 なんで閉じちゃった？

2020-10-14 04:04 UTC, ono-hikaru81 commented
作ってる途中で間違ってenter押してしまって焦って閉じてしまいました

2020-10-14 05:14 UTC, taishi-matsumura commented
reopenしておきますー

2020-10-15 00:54 UTC, ono-hikaru81 commented
フェードイン、フェードアウト、カラーフェイドの実装をしたので、コードの確認をお願いします。
カラーフェイドは微妙な出来具合になっています。

2020-10-15 04:42 UTC, taishi-matsumura commented
- [ ] 元となるIssueの番号をタイトルに記載してください。
- [ ] PRの作業完了後に元となるIssueを閉じて良いのであれば、紐付けをしてください。
- [ ] PRの本文に実装方針を書いてください。

2020-10-15 04:50 UTC, taishi-matsumura requested changes
フェード処理に限らず、ゲームの処理は全て「1フレームごとに呼ばれるもの」という想定で実装する必要があります。1秒間に60回回るメインループから呼び出されるという前提で、「そのフレームで何をするか」という視点で実装するようにしてください。

これはゲーム特有のコーディングですが、絶対に押さえておかないといけない重要なポイントです。

2020-10-15 04:50 UTC, taishi-matsumura commented on action/Action/DrawManager.cpp
> +void Fade_in(int R,int G,int B)
フェードイン/フェードアウトは一つの関数に纏めてしまい、引数で指定できるようにすればスッキリすると思います。

2020-10-15 04:50 UTC, taishi-matsumura commented on action/Action/DrawManager.cpp
> +	while (true)
1フレームの処理の中でフェード処理を最後までやりきってしまうような関数になっているのでNGです。

2020-10-15 05:19 UTC, taishi-matsumura commented on action/Action/DrawManager.h
> +void Fade_color(); // �J���[�t�F�C�h
関数名が
* 大文字始まり
* 単語の区切りはアンダースコア( `_` )
* 先頭以外の単語は小文字始まり

となっており、他の関数の命名との乖離が激しいです。正解はありませんが、プロジェクト内で統一性は持たせてください。
一般的には、関数名は[パスカルケース](https://ja.wikipedia.org/wiki/キャメルケース)にすることが多いです。

2020-10-22 02:38 UTC, taishi-matsumura requested changes
命名・空白・改行等、体裁に関する指摘ばかりですが、修正お願いします。

2020-10-22 02:38 UTC, taishi-matsumura commented on action/Action/DrawManager.h
> +class Fade
将来的にこのファイルにDrawManagerクラスを作成する予定ですか？
そうでないのであれば、クラス名とファイル名は合わせた方が良いです。
また、基本的に『1ファイルに1クラス』を心がけましょう。

2020-10-22 02:38 UTC, taishi-matsumura commented on action/Action/DrawManager.cpp
> +// �t�F�[�h�C��,�t�F�[�h�A�E�g
日本語なので、
```
// フェードイン、フェードアウト
```
の方が良いです。

2020-10-22 02:38 UTC, taishi-matsumura commented on action/Action/DrawManager.h
> +	bool m_nowFading;
ブサイクです。
```suggestion
	bool m_isFading;
```
はいかがでしょう。

2020-10-22 02:38 UTC, taishi-matsumura commented on action/Action/DrawManager.h
> +public:
ここは間に空白行を入れる方が一般的かと思います。

2020-10-22 02:38 UTC, taishi-matsumura commented on action/Action/DrawManager.h
> +
この空白行は不要。

2020-10-22 02:38 UTC, taishi-matsumura commented on action/Action/Main.cpp
> +		ScreenFlip();
行末に不要な空白があるので消しましょう。

2020-10-22 02:38 UTC, taishi-matsumura commented on action/Action/DrawManager.cpp
> +		if(ProcessMessage() == -1) break;
`if` と `(` の間のスペースの有無を統一してください。

2020-10-22 02:38 UTC, taishi-matsumura commented on action/Action/DrawManager.h
> +	bool IsFading();
publicな関数はクラス外から呼ばれることを想定しているはずなので、そのクラスを用いてコードを書くPG向けのコメントを書くようにしましょう。
C++であればJavaDoc形式のdoxygenコメントを書くのが一般的ですが、三好や私のようにxmlコメントで書いても良いと思います。

2020-10-22 02:38 UTC, taishi-matsumura commented on action/Action/DrawManager.h
> +class Fade
public関数同様、クラスにも説明のコメントを書くのが一般的です。

2020-10-22 02:38 UTC, taishi-matsumura commented on action/Action/DrawManager.cpp
> +		if (R >= 0 && R < 256 && G >= 0 && G < 256 && B >= 0 && B < 256) // RGB��0 �` 256�̎�
```
// RGBが0 ～ 256の時
```
コメント部分ですが、RGBの最大値は256ではないはず

2020-10-22 02:39 UTC, taishi-matsumura commented on action/Action/DrawManager.cpp
> +	case 0:
0や1といったマジックナンバーで処理を切り分けるのはやめましょう。
enumを作るのが一般的です。

2020-10-26 00:45 UTC, ono-hikaru81 commented on action/Action/Main.cpp
> +		ScreenFlip();
空白を削除しました。

2020-10-26 00:45 UTC, ono-hikaru81 commented on action/Action/DrawManager.h
> +
空白行を削除しました。

2020-10-26 00:46 UTC, ono-hikaru81 commented on action/Action/DrawManager.h
> +public:
空白行を入れました。

2020-10-26 00:46 UTC, ono-hikaru81 commented on action/Action/DrawManager.cpp
> +// �t�F�[�h�C��,�t�F�[�h�A�E�g
読点に修正しました。

2020-10-26 00:52 UTC, ono-hikaru81 commented on action/Action/DrawManager.h
> +class Fade
fade.hとcppを作ってそこに移しました。

2020-10-26 01:08 UTC, ono-hikaru81 commented on action/Action/DrawManager.h
> +	bool IsFading();
コメントを追加しました。

2020-10-26 01:10 UTC, ono-hikaru81 commented on action/Action/DrawManager.h
> +class Fade
何のクラスなのかを追記しました。

2020-10-26 01:21 UTC, taishi-matsumura commented on action/Action/DrawManager.h
> +class Fade
DrawManager.h/.cppにDrawManagerクラスが居ないのが気持ち悪いですが、C言語で書き始めて途中からC++を導入したプロジェクトなので仕方ないですね。
今回は良しとしましょう。

2020-10-26 01:24 UTC, taishi-matsumura commented on action/Action/DrawManager.h
> +	bool IsFading();
普通C/C++形式のコメントにしたのですね。
今回は良しとしますが、次回からはdoxygen等のドキュメント自動生成ツールに対応したコメントを書いていくようにしましょう。

2020-10-26 01:53 UTC, ono-hikaru81 commented on action/Action/DrawManager.cpp
> +	case 0:
swithを消してenumにしました。
183ed4f7

2020-10-26 03:07 UTC, ono-hikaru81 commented on action/Action/DrawManager.h
> +	bool m_nowFading;
提案して頂いたものに変更しました。
2861269a

2020-10-26 03:16 UTC, taishi-matsumura commented on action/Action/DrawManager.cpp
> +	case 0:
是正NGです。
フェードの種類を表すenumを作って関数内でもそれを使っているのであれば、引数の型もenumにしないと意味がありません。

2020-10-28 05:49 UTC, ono-hikaru81 commented on action/Action/DrawManager.cpp
> +	case 0:
310518f8 - switchに戻してマジックナンバーを変数名に変更しました。

2020-10-29 00:26 UTC, taishi-matsumura commented on action/Action/DrawManager.cpp
> +	case 0:
指摘の本題は
> 引数の型もenumにしないと意味がありません。

ですので、こちらの修正をお願いします。

2020-10-29 01:02 UTC, ono-hikaru81 commented on action/Action/DrawManager.cpp
> +	case 0:
9f0ce87 - 引数の型をenumに修正しました。

2020-10-29 02:38 UTC, taishi-matsumura commented on action/Action/Fade.cpp
> +		m_fadeType = 0;
フェード種別を0/1で表現するのをやめてenumに変えたのですから、
```suggestion
		m_fadeType = fadeType;
```
では？
また、そうなると `m_fadeOut` もint型ではなくなりますね。

この部分は `case fadeOut` のときも同様なので、関数の最後で纏めてしまえば良さそうですね。
`m_isFading = true;` も共通なので纏めましょう。
DRYの原則です！！

2020-11-02 00:53 UTC, ono-hikaru81 commented on action/Action/Fade.cpp
> +		m_fadeType = 0;
演算子を使って纏めました。

2020-11-07 14:03 UTC, taishi-matsumura reviewed
「フェードは一旦これで終わらせたい」とのことですので、指摘事項については別Issueで対応とし、コミット整理に着手してもかまいません。
その場合、授業内で話したように現時点でのコードを別branchとして保存しpushしておいてもらえると、コミット整理前後でコードが変わっていないことが確認できるので安心ですね。

指摘事項に関してはヒドイ内容(「ウンコード」と呼ばれるもの)が多いので、本PRで対応しないにせよ最終的には是正してくださいね。

2020-11-07 14:03 UTC, taishi-matsumura commented on action/Action/Fade.cpp
> +	}
複数の条件のうち起こりうるのが一つだけの場合は、if-else ifやif-elseを使うようにしましょう。
別のif文を連続させるのは、どちらにも入る可能性がある場合のみにすべきです。

「複数の事象が同時に発生し得るか否か」というのはプログラムの仕様上非常に重要です。
「書いた本人が知っている」のは当然ですが、「書いた本人**しか**知らない」のは困ります。
詳細を知らない人がコードを読んでもひと目で区別できるようにしましょう。

2020-11-07 14:03 UTC, taishi-matsumura commented on action/Action/Fade.cpp
> +	}
if文の中身は全く同じようですので、 `||` を使う等して共通化してください。
Don't Repeat Yourself！

2020-11-07 14:03 UTC, taishi-matsumura commented on action/Action/Fade.cpp
> +	}
ここも重複コードが多いように思います。
「符号が逆なだけ」「範囲が異なるだけ」等も重複と見做してください。

その上で、共通化したコードと敢えて重複させたコードのどちらを採用するかを可読性等の観点から比較検討すべきです。

2020-11-07 14:03 UTC, taishi-matsumura commented on action/Action/Processing.cpp
> +		fade.IsFading();
true/falseを返す関数を呼ぶだけのコードになっており、意味がありません。
下のif文と合わせて
```
if(!fade.IsFading())
```
 では？
L.45も同様です。

2020-11-07 14:03 UTC, taishi-matsumura commented on action/Action/Processing.cpp
> +	}
例によって重複コードです。

2020-11-07 14:03 UTC, taishi-matsumura commented on action/Action/Fade.h
> +	int m_fadeType;
カプセル化できませんか？

2020-11-11 00:40 UTC, taishi-matsumura approved these changes

2020-11-11 00:42 UTC, taishi-matsumura commented
絶対pathが残っているのを見落としていました…
このPRはmergeしておくので、新たにIssue立てて対応してください！

2020-11-11 00:42 UTC, merged