READMEを更新
human-osaka-game-2020/ActionGame_ono pull request #6
Opened 2020-10-15 02:07 UTC by ono-hikaru81

READMEにDXライブラリのダウンロードサイトとDXライブラリの構築手順が記載されているサイトのリンクを書きました。

2020-10-15 02:09 UTC, taishi-matsumura requested changes
修正してください。

2020-10-15 02:09 UTC, taishi-matsumura commented on README.md
> +１．まずは下記のサイトからDxLibをダウンロードしてください。<br>
htmlではなくmarkdownなので、brタグを使う必要は無いです。
別の方法で改行を実現してください。

2020-10-15 04:36 UTC, taishi-matsumura commented on README.md
> +[DXライブラリの構築手順](https://dxlib.xsrv.jp/dxuse.html)
ピリオドの後ろに半角スペースを入れると番号付きリストになるので、それを使いましょう。
そうすれば、下記のように全て `1.` と書いても自動的に連番にしてくれます。
```suggestion
1. まずは下記のサイトからDxLibをダウンロードしてください。  
[DXライブラリのダウンロード](https://dxlib.xsrv.jp/dxdload.html)

1. ダウンロードが終わったら下記のサイトに従って構築していきます。  
[DXライブラリの構築手順](https://dxlib.xsrv.jp/dxuse.html)
```

番号付きリストに限らず、Markdownをプレビュー画面で見て期待通りになっていなければ何かがおかしいので、都度プレビューを見て確認する癖をつけてください。

2020-10-20 02:44 UTC, taishi-matsumura commented on README.md
> +# DxLibの構築手順
DxLibのインストール手順しか書かれていませんが、環境変数の登録やVisualStudio側の設定は不要でしょうか。
必要なのであれば記載しておきましょう。

2020-10-20 12:44 UTC, ono-hikaru81 commented on README.md
> +# DxLibの構築手順
環境変数の登録とVisualStudio側の設定は2つ目のサイトのほうに記載されてあると思うのですが、それではないのでしょうか？

2020-10-20 14:07 UTC, taishi-matsumura commented on README.md
> +# DxLibの構築手順
環境変数については、[三好のREADME](https://github.com/human-osaka-game-2020/TrapAction_Miyoshi)を参考にしてみてください。
これが唯一の方法というわけでは無いですが、よく用いられる手法です。

いずれにせよ、目的は「誰のPCでもビルドできる手順を確立する」ということです。

2020-10-22 03:19 UTC, ono-hikaru81 commented on README.md
> +[DXライブラリの構築手順](https://dxlib.xsrv.jp/dxuse.html)
番号付きリストになるようにしました。

2020-10-22 03:19 UTC, ono-hikaru81 commented on README.md
> +# DxLibの構築手順
環境変数の設定の仕方を追加しました。

2020-11-11 15:48 UTC, taishi-matsumura approved these changes

2020-11-11 15:48 UTC, taishi-matsumura commented
閉じ忘れていました。
やっておきます。

2020-11-11 15:58 UTC, merged